"""empty message

Revision ID: cc542df161fc
Revises: 30c7d0c34c1f
Create Date: 2019-12-17 21:00:45.103967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc542df161fc'
down_revision = '30c7d0c34c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Admin', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Admin', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
